# Generated by Django 3.1.7 on 2021-03-10 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('time', models.IntegerField(verbose_name='Time')),
                ('f1', models.IntegerField(verbose_name='f1')),
                ('f2', models.IntegerField(verbose_name='f2')),
                ('f3', models.IntegerField(verbose_name='f3')),
                ('result', models.IntegerField(verbose_name='Result')),
            ],
        ),
    ]
